name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service with OpedID. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 3.0.0-beta.1
homepage: https://github.com/d3xt3r2909/linkedin_login
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.24.0-6.0.pre"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  meta: ^1.15.0
  rxdart: ^0.28.0
  uuid: ^4.5.1
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.9
  webview_flutter_wkwebview: ^3.15.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.25.7
  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
